GET http://localhost:3000/tasks?search

###

POST http://localhost:3000/tasks

{
  "title": "Fazer um bolo",
  "description": "Misture os ingredientes secos (farinha, açúcar, fermento em pó) em um recipiente. Em outro recipiente, misture os ingredientes úmidos (ovos, leite, óleo). Combine os ingredientes secos e úmidos até formar uma massa homogênea. Despeje a massa em uma forma untada e enfarinhada. Asse em forno pré-aquecido a 180°C por cerca de 30 minutos, ou até dourar."
}

###

DELETE http://localhost:3000/tasks/e4303ef1-2c9b-4239-834f-c97a9f68a617

###

PATCH http://localhost:3000/tasks/6f9cbd28-b31e-477b-922d-0d8e1e42aef0/complete